In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv('insurance_data.csv')

In [3]:
df.head()

age  bought_insurance
0   22                 0
1   25                 0
2   47                 1
3   52                 0
4   46                 1

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X=df['age']
y = df['bought_insurance']

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [12]:
X_train_scaled = X_train.copy()
X_train_scaled = X_train_scaled/100;
X_test_scaled = X_test.copy()
X_test_scaled = X_test_scaled/100;

In [13]:
X_train_scaled

26    0.23
20    0.21
14    0.49
7     0.60
15    0.55
5     0.56
19    0.18
18    0.19
13    0.29
8     0.62
0     0.22
6     0.55
23    0.45
21    0.26
24    0.50
11    0.28
3     0.52
25    0.54
Name: age, dtype: float64

In [15]:
X_train_scaled.shape

(18,)

In [18]:
import tensorflow as tf
from tensorflow import keras

In [23]:
model = keras.Sequential([
    keras.layers.Dense(1,input_shape =(1,),activation='sigmoid',kernel_initializer = 'ones',bias_initializer ='zeros' )])
model.compile(optimizer='adam',
             loss ='binary_crossentropy',
             metrics=['accuracy'])
model.fit(X_train_scaled,y_train,epochs=5000)

Epoch 1/5000
1/1 [==============================] - 0s 437ms/step - loss: 0.6779 - accuracy: 0.4444
Epoch 2/5000
1/1 [==============================] - 0s 13ms/step - loss: 0.6777 - accuracy: 0.4444
Epoch 3/5000
1/1 [==============================] - 0s 14ms/step - loss: 0.6776 - accuracy: 0.4444
Epoch 4/5000
1/1 [==============================] - 0s 19ms/step - loss: 0.6774 - accuracy: 0.4444
Epoch 5/5000
1/1 [==============================] - 0s 12ms/step - loss: 0.6773 - accuracy: 0.4444
Epoch 6/5000
1/1 [==============================] - 0s 13ms/step - loss: 0.6771 - accuracy: 0.4444
Epoch 7/5000
1/1 [==============================] - 0s 10ms/step - loss: 0.6769 - accuracy: 0.4444
Epoch 8/5000
1/1 [==============================] - 0s 20ms/step - loss: 0.6768 - accuracy: 0.4444
Epoch 9/5000
1/1 [==============================] - 0s 20ms/step - loss: 0.6766 - accuracy: 0.4444
Epoch 10/5000
1/1 [==============================] - 0s 9ms/step - loss: 0.6765 - accuracy: 0.4444
Epoch 11/

In [24]:
model.evaluate(X_test_scaled,y_test)

1/1 [==============================] - 0s 247ms/step - loss: 0.5450 - accuracy: 0.7778


[0.5449538826942444, 0.7777777910232544]

In [25]:
model.predict(X_test_scaled)

1/1 [==============================] - 0s 103ms/step


array([[0.15226907],
       [0.24491246],
       [0.22144556],
       [0.22144556],
       [0.5467032 ],
       [0.43234423],
       [0.5303861 ],
       [0.75150657],
       [0.7129325 ]], dtype=float32)

In [34]:
X_test_scaled

10    0.18
12    0.27
16    0.25
1     0.25
2     0.47
22    0.40
4     0.46
9     0.61
17    0.58
Name: age, dtype: float64

In [28]:
coef,intercept = model.get_weights()

In [29]:
coef

array([[6.566459]], dtype=float32)

In [30]:
intercept

array([-2.898877], dtype=float32)

In [32]:
def sigmoid(x):
    import math
    return 1/(1+math.exp(-x))
sigmoid(18)

0.9999999847700205

In [33]:
def prediction(age):
    weighted_sum = coef[0]*age+intercept
    return sigmoid(weighted_sum)

In [35]:
prediction(0.18)

0.15226906428298556

In [36]:
def log_loss(y_true, y_predicted):
    epsilon = 1e-15
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [43]:
def sigmoid_numpy(X):
   return 1/(1+np.exp(-X))

sigmoid_numpy(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

In [46]:
def gradient_descent(age, y_true, epochs, loss_thresold):
    w1 = w2 = 1
    bias = 0
    rate = 0.5
    n = len(age)
    for i in range(epochs):
        weighted_sum = w1 * age  + bias
        y_predicted = sigmoid_numpy(weighted_sum)
        loss = log_loss(y_true, y_predicted)

        w1d = (1/n)*np.dot(np.transpose(age),(y_predicted-y_true)) 
     

        bias_d = np.mean(y_predicted-y_true)
        w1 = w1 - rate * w1d
 
        bias = bias - rate * bias_d

        print (f'Epoch:{i}, w1:{w1}, bias:{bias}, loss:{loss}')

        if loss<=loss_thresold:
            break

    return w1, w2, bias


In [47]:
gradient_descent(X_train_scaled,y_train,1000, 0.4631)

Epoch:0, w1:0.9963307395056789, bias:-0.0770976088087999, loss:0.6779015141698728
Epoch:1, w1:0.9964321869392735, bias:-0.14474645986551785, loss:0.6667270865986719
Epoch:2, w1:0.9998142823039734, bias:-0.20416811527209994, loss:0.658129673659523
Epoch:3, w1:1.0060319838384708, bias:-0.2564669731054122, loss:0.6514581524025058
Epoch:4, w1:1.0146885563865555, bias:-0.30262407198422386, loss:0.6462163307110969
Epoch:5, w1:1.02543491824446, bias:-0.34350015354409447, loss:0.6420310808489448
Epoch:6, w1:1.0379667300294513, bias:-0.3798438946768733, loss:0.6386244492168276
Epoch:7, w1:1.0520203680744393, bias:-0.41230257583467034, loss:0.6357907409711326
Epoch:8, w1:1.067368505016034, bias:-0.4414334823302669, loss:0.6333784256666097
Epoch:9, w1:1.0838157245727982, bias:-0.46771505093553195, loss:0.6312762173444536
Epoch:10, w1:1.1011944024635432, bias:-0.49155724002355433, loss:0.6294025515735889
Epoch:11, w1:1.119360963175301, bias:-0.5133108897732618, loss:0.6276977240865818
Epoch:12, w1

(4.865539371339161, 1, -2.1644083996618972)