In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import warnings 
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv('spam.csv')

In [4]:
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [6]:
df.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [7]:
df['spam'] = df.Category.apply(lambda x : 1 if x == 'spam' else 0)

In [8]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(df.Message,df.spam,test_size = 0.25)

In [11]:
from sklearn.feature_extraction.text import CountVectorizer

In [12]:
v = CountVectorizer()

In [13]:
X_train_count = v.fit_transform(X_train.values)

In [14]:
X_train_count.toarray()[:3]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [16]:
from sklearn.naive_bayes import MultinomialNB

In [17]:
model = MultinomialNB()

In [18]:
model.fit(X_train_count,y_train)

MultinomialNB()

In [23]:
emails = [
    'Go until jurong point, crazy.. Available only', 
    'Ok lar... Joking wif u oni..',
    'Upto 20% discount on kids section clothing'
]
emails_count = v.transform(emails)

In [24]:
model.predict(emails_count)

array([0, 0, 1], dtype=int64)

In [25]:
X_test_count = v.transform(X_test)

In [26]:
model.score(X_test_count,y_test)

0.9849246231155779

In [27]:
from sklearn.pipeline import Pipeline

In [28]:
clf = Pipeline([
    ('vectorizer',CountVectorizer()),
    ('nb',MultinomialNB())
])

In [31]:
clf.fit(X_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [32]:
clf.score(X_test,y_test)

0.9849246231155779

In [33]:
clf.predict(emails)

array([0, 0, 1], dtype=int64)