<a href="https://colab.research.google.com/github/Manvi234/ML-Concepts/blob/main/Words2NumbersSupervivedTechnique.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
import tensorflow_hub as hub
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential
import PIL.Image as Image
import os
import cv2

In [2]:
rest_reviews = ['nice food',
                'amazing restaurant',
                'too good',
                'just loved it',
                'will go again',
                'horrible food',
                'never go there',
                'poor service',
                'poor quality',
                'needs improvement']
senitiment = [1,1,1,1,1,0,0,0,0,0]

In [3]:
from tensorflow.keras.preprocessing.text import one_hot
one_hot('amazing restaurant',30)#30 is vocab size

[13, 12]

In [4]:
vocabulary_size = 30
encoded_reviews =[]
for d in rest_reviews:
  encoded_reviews.append(one_hot(d,vocabulary_size))
  
encoded_reviews

[[10, 26],
 [13, 12],
 [3, 3],
 [17, 17, 17],
 [6, 24, 11],
 [21, 26],
 [16, 24, 20],
 [11, 29],
 [11, 10],
 [23, 18]]

In [5]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [19]:
max_length = 4
padded_reviews = pad_sequences(encoded_reviews,maxlen = max_length,padding='post')
print(padded_reviews)

[[10 26  0  0]
 [13 12  0  0]
 [ 3  3  0  0]
 [17 17 17  0]
 [ 6 24 11  0]
 [21 26  0  0]
 [16 24 20  0]
 [11 29  0  0]
 [11 10  0  0]
 [23 18  0  0]]


In [20]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dense

In [21]:
embedded_vector_size = 5
model = Sequential()
model.add(Embedding(vocabulary_size,embedded_vector_size,input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1,activation='sigmoid'))

In [26]:
X=padded_reviews
y = np.array(senitiment)

In [33]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [34]:
print(model.summary())

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 5)              150       
                                                                 
 flatten_2 (Flatten)         (None, 20)                0         
                                                                 
 dense_1 (Dense)             (None, 1)                 21        
                                                                 
Total params: 171
Trainable params: 171
Non-trainable params: 0
_________________________________________________________________
None


In [48]:
model.fit(X, y, epochs=50, verbose=0)

In [55]:
loss,accuracy = model.evaluate(X,y)
print(loss)
print(accuracy)

1/1 [==============================] - 0s 31ms/step - loss: 0.4867 - accuracy: 1.0000
0.48665302991867065
1.0


In [57]:
weights = model.get_layer('embedding').get_weights()[0]

In [58]:
weights

array([[ 1.65919676e-01,  1.85424447e-01,  1.12149574e-01,
        -1.81627586e-01, -1.78847358e-01],
       [-1.32470839e-02,  2.33375095e-02,  2.67919414e-02,
        -1.64731033e-02, -3.58300693e-02],
       [-2.51972321e-02, -6.09116629e-03,  4.67910208e-02,
        -4.26556952e-02,  3.12932394e-02],
       [-1.26231134e-01, -6.79975748e-02, -1.93183511e-01,
        -1.38953134e-01,  2.00527117e-01],
       [ 4.39533480e-02, -1.70284137e-02,  2.94907354e-02,
        -5.14211506e-03, -9.69590992e-03],
       [ 3.53695042e-02, -3.21922675e-02,  2.39195712e-02,
         3.08395289e-02, -2.01812871e-02],
       [-1.43461570e-01,  1.76034853e-01, -2.03822389e-01,
        -1.46332815e-01, -1.83070093e-01],
       [ 4.56742384e-02, -4.36010845e-02, -4.98462096e-02,
         4.20796387e-02, -2.71818638e-02],
       [ 5.51559776e-03,  3.79256718e-02,  2.55835690e-02,
        -9.18023288e-05, -1.26672871e-02],
       [ 2.26826929e-02,  3.04719545e-02,  2.36063339e-02,
        -2.49961019e-02

In [59]:
len(weights)

30

In [60]:
weights[10]

array([-0.04764473,  0.23776826, -0.12462544, -0.20790571, -0.19498263],
      dtype=float32)

In [61]:
weights[13]

array([-0.15143715,  0.1893738 , -0.13403746, -0.16810022, -0.16336823],
      dtype=float32)